# Generated by Django 4.1.5 on 2023-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_delete_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
