# Generated by Django 4.1.5 on 2023-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurant_restaurant_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
