# Generated by Django 4.1.5 on 2023-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_restaurant_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_license',
            field=models.ImageField(upload_to='restaurant/licenses'),
        ),
    ]
