# Generated by Django 4.1.5 on 2023-02-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_openinghour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('restaurant', 'day', 'from_hour', 'to_hour')},
        ),
    ]
