# Generated by Django 4.1.5 on 2023-01-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
    ]
