# Generated by Django 4.1.5 on 2023-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/profile_pics/default-food.png', null=True, upload_to='users/profile_pics'),
        ),
    ]
