# Generated by Django 4.1.5 on 2023-02-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-modified_on', '-added_on'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_title',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='food_title',
        ),
    ]
