# Generated by Django 4.1.5 on 2023-03-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_openinghour_options'),
        ('orders', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(blank=True, to='core.restaurant'),
        ),
    ]
