# Generated by Django 4.1.5 on 2023-03-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_choice',
        ),
    ]
